[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "visualastro"
version = "0.3.0"
description = "Astro data analysis and plotting package"
authors = [
    {name = "Elko Gerville-Reache", email = "elkogerville@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "astropy",
    "matplotlib",
    "numpy",
    "scipy",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
]
images = [
    "regions",
    "reproject",
]
spectralcube = [
    "spectral_cube",
    "regions",
    "reproject",
]
spectra = [
    "specutils",
    "dust_extinction",
]
styles = [
    "scienceplots",
]
utils = [
    "cmasher",
    "colorspacious",
    "tol-colors",
    "tqdm",
]
all = [
    "cmasher",
    "colorspacious",
    "dust_extinction",
    "regions",
    "reproject",
    "scienceplots",
    "spectral_cube",
    "specutils",
    "tol-colors",
    "tqdm",
]

[project.urls]
Homepage = "https://github.com/elkogerville/VisualAstro"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
exclude = [
    "tests*",
    "tests*",
    "build*",
    "dist*",
]

[tool.setuptools.package-data]
"visualastro" = [
    "stylelib/*.mplstyle",
    "stylelib/**/LICENSE",
    "stylelib/fontlib/**/*.ttf",
    "stylelib/fontlib/**/*.otf",
    "stylelib/fontlib/**/LICENSE",
    "data/**/*.png",
    "data/**/*.jpg",
    "*.md",
    "LICENSE",
]

[tool.setuptools.exclude-package-data]
"*" = [
    "*.egg-info/*",
    "*.egg-info",
    "EGG-INFO/*",
]
